version: 1.1.0+{build}
image: Visual Studio 2017
configuration: CI
before_build:
- cmd: dotnet restore
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: 7exHzq8I96c5RKQn+R6bho0U4DdjiO/vEvdZtXge+dmoHMhzIHzgEX+uDl1zuKj/
  on:
    branch: master
