dist: trusty
sudo: false
language: csharp
solution: Guard.sln
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.0.5
mono: none
dotnet: 2.1.400
script:
- dotnet test tests/ -c Release
